### ISSUE TITLE
EJS <% include page %> kullan

### ISSUE THREAD

**Issue by lugrugzo** [tunaakgul/tuna-dictionary#1]
Mesela her sayfada `<head>` içinde js/css falan çağırıyorsun. Ortak olan kütüphaneleri libraries.html gibi bir sayfaya koy. Daha sonra çağırmak istediğin tekil sayfalarda:

``` html

<% include libraries %>

``` 

Diye `<head>` içinde çağır.

**Comment by tunaakgul** [comment]
1-2 gün içinde genel bir düzenleme yapacağım, teşekkürler.
